---
output:
  html_document: default
  pdf_document: default
---
Time Series Part
=====================

## Load Data

```{r, echo=FALSE}
library(data.table)
data <- fread("../data/caracteristics.csv",encoding = 'UTF-8')
data <- data.table(data)
data <- na.omit(data)
data <- data[,c('Num_Acc','mois','an','jour')]
names(data) <- c('id','month','year','day')
data[,'year'] <- data[,'year']+2000
data <- within(data, date <- sprintf("%d-%02d-01", year, month))
data$date <- as.Date(data$date,format="%Y-%m-%d")
data <- as.data.table(data)
data_datecnt <- data[,.N,by=c("date","year","month")]
```

## Effects of month
```{r, echo=FALSE, warning=FALSE}
library(ggplot2)
avg <- stat_summary(aes(group = 1), fun.y = "mean", geom = "line", 
colour = "red", size = 2, na.rm = TRUE) 
data_datecnt$year <- as.factor(data_datecnt$year)
line <- geom_smooth(aes(group = 1),method=lm) #Looking for linear trend
ggplot(data_datecnt, aes(as.factor(month), N, group = year)) + 
  geom_line(aes(colour = year)) +geom_point(aes(colour = year))+ 
  avg+ line + ggtitle("Number of accidents by month with seasonal trendline") + labs(x='month',y='Number')

```


## Original data fornumber of accidents by month

```{r, echo=FALSE, warning=FALSE}
library(scales)
library(ggplot2)
ggplot(data_datecnt,aes(x=date,y=N,group = 1)) + geom_line() + geom_point()+ scale_x_date(labels = date_format("%Y-%m")) + ggtitle("Number of accidents by month from 2005 to 2016 in France")+ labs(x='month',y='Number')
```


## Month of year effect
```{r,echo = FALSE, encoding = "utf-8"}
deseas <- function(var, month) {
	resid(lm(var ~ factor(month), na.action = "na.exclude")) + mean(var,na.rm = TRUE)
}
data_datecnt[,N_ds:=deseas(N,month)]
ggplot(data_datecnt,aes(x=date,y=N_ds,group = 1)) + geom_line() + geom_point()+ scale_x_date(labels = date_format("%Y-%m")) + ggtitle("Deseasonalized number of accidents by month from 2005 to 2016 in France") + labs(x='month',y='Number')
```

