---
output:
  html_document: default
  pdf_document: default
---
Time Series Part
=====================

## Load Data

```{r, echo=FALSE}
library(data.table)
library(stats)
data_char <- data.table(fread("../data/caracteristics.csv",encoding = 'UTF-8'))
data_char <- na.omit(data_char)[,c('Num_Acc','lum','atm','col','an','mois','jour')]
names(data_char) <- c('id','lighting','atmosphere','collision','year','month','day')

data_users <- data.table(fread("../data/users.csv",encoding = 'UTF-8'))
data_users <- na.omit(data_users)[,c('Num_Acc','grav')]
names(data_users) <- c('id','fatality')

data <- merge(x = data_char, y = data_users, by = "id", all = TRUE)

data$fatality = 2 == data$fatality
data <- data[data[, .I[which.max(fatality)],by=id]$V1]
data <- na.omit(data)
head(data,20)
```



## relationship between collision types and other variables
```{r,echo = FALSE, encoding = "utf-8",fig.width=10, fig.height=8}
data_check = data


# table(data_check$lighting,data_check$collision)
ggplot(data_check) + geom_bar(position="fill") + aes(factor(data_check$lighting), fill=factor(data_check$collision))  + coord_flip() + labs( x = "Lighting Conditions", fill='Collision Types')+ scale_x_discrete(labels=c("1" = "Full day", "2" = "Twilight or dawn","3" = "Night without public lighting","4"="Night with public lighting not lit","5"="Night with public lighting on")) + scale_fill_discrete(labels = c("1" = "Two vehicles - frontal", "2" = "Two vehicles - from the rear","3" = "Two vehicles - by the side","4"="Three vehicles and more - in chain","5"="Three or more vehicles - multiple collisions","6"="Other collision","7"="Without collision"))

ggplot(data_check) + geom_bar(position="fill") + aes(factor(data_check$atmosphere), fill=factor(data_check$collision))  + coord_flip() + labs( x = "Atmosphere Conditions", fill='Collision Types')+ scale_x_discrete(labels=c("1" = "Normal", "2" = "Light rain","3" = "Heavy rain","4"="Snow - hail","5"="Fog - smoke","6"="Strong wind - storm","7"="Dazzling weather","8"="Cloudy weather","9"="Other")) + scale_fill_discrete(labels = c("1" = "Two vehicles - frontal", "2" = "Two vehicles - from the rear","3" = "Two vehicles - by the side","4"="Three vehicles and more - in chain","5"="Three or more vehicles - multiple collisions","6"="Other collision","7"="Without collision"))
```
