---
output:
  html_document: default
  pdf_document: default
---
Time Series Part
=====================

## Load Data

```{r, echo=FALSE}
library(data.table)
library(stats)
data_char <- data.table(fread("../data/caracteristics.csv",encoding = 'UTF-8'))
data_char <- na.omit(data_char)[,c('Num_Acc','lum','atm','col','an','mois','jour')]
names(data_char) <- c('id','lighting','atmosphere','collision','year','month','day')

data_users <- data.table(fread("../data/users.csv",encoding = 'UTF-8'))
data_users <- na.omit(data_users)[,c('Num_Acc','grav')]
names(data_users) <- c('id','fatality')

data <- merge(x = data_char, y = data_users, by = "id", all = TRUE)

data$fatality = 2 == data$fatality
data <- data[data[, .I[which.max(fatality)],by=id]$V1]
data <- na.omit(data)
head(data,20)
```

## Effects of lighting
```{r, echo=FALSE, warning=FALSE}
f_rate <- function(vec){
  length(vec[vec==TRUE])/length(vec)
}
rate_lighting <- aggregate(data$fatality, by=list(data$lighting) ,FUN= function(z) f_rate(z))
rate_lighting$Group.1 <- as.factor(rate_lighting$Group.1)
library(ggplot2)
library(scales)
ggplot(rate_lighting,aes(Group.1, x))+geom_col()+ scale_x_discrete(labels=c("1" = "Full day", "2" = "Twilight or dawn","3" = "Night without public lighting","4"="Night with public lighting not lit","5"="Night with public lighting on")) + theme(axis.text.x = element_text(angle = 90, hjust = 1))+labs(x ="Lighting Conditions", y = "Fatal Rate")
```


## effect of atmosphere

```{r, echo=FALSE, warning=FALSE}
rate_atmosphere <- aggregate(data$fatality, by=list(data$atmosphere) ,FUN= function(z) f_rate(z))
rate_atmosphere$Group.1 <- as.factor(rate_atmosphere$Group.1)
library(ggplot2)
library(scales)
ggplot(rate_atmosphere,aes(Group.1, x))+geom_col()+ scale_x_discrete(labels=c("1" = "Normal", "2" = "Light rain","3" = "Heavy rain","4"="Snow - hail","5"="Fog - smoke","6"="Strong wind - storm","7"="Dazzling weather","8"="Cloudy weather","9"="Other")) + theme(axis.text.x = element_text(angle = 90, hjust = 1))+labs(x ="Atmosphere Conditions", y = "Fatal Rate")
```


## effect of collision type
```{r,echo = FALSE, encoding = "utf-8"}
rate_collision <- aggregate(data$fatality, by=list(data$collision) ,FUN= function(z) f_rate(z))
rate_collision$Group.1 <- as.factor(rate_collision$Group.1)
library(ggplot2)
library(scales)
ggplot(rate_collision,aes(Group.1, x))+geom_col()+ scale_x_discrete(labels=c("1" = "Two vehicles - frontal", "2" = "Two vehicles - from the rear","3" = "Two vehicles - by the side","4"="Three vehicles and more - in chain","5"="Three or more vehicles - multiple collisions","6"="Other collision","7"="Without collision")) + theme(axis.text.x = element_text(angle = 90, hjust = 1))+labs(x ="Collision Conditions", y = "Fatal Rate")
```





